#!/bin/bash

BOT_TOKEN=""

CHANNEL_ID=""

MESSAGE="I'm Elite TV Woman :3"

curl -X POST -H "Content-Type: application/json" -H "Authorization: Bot $BOT_TOKEN" \
-d "{\"content\":\"$MESSAGE\"}" \
"https://discord.com/api/v10/channels/$CHANNEL_ID/messages"
